// src/app/layout.js
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-900 text-white min-h-screen">
          <header className="bg-gradient-to-r from-orange-500 to-orange-600 p-6">
            <div className="flex justify-between items-center">
              <div className="flex items-center">
                <img src="/images/logo.png" alt="Logo" className="h-16 mr-4" />
                <h1 className="text-4xl font-bold text-white">
                  NEXTLEVEL FOOD
                </h1>
              </div>
              <nav>
                <Link
                  href="/browse-meals"
                  className="mr-6 text-white hover:text-orange-500"
                >
                  Browse Meals
                </Link>
                <Link
                  href="/foodies-community"
                  className="text-white hover:text-orange-500"
                >
                  Foodies Community
                </Link>
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
